import os
import subprocess
import shutil

REPOS_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), "repos")
os.makedirs(REPOS_DIR, exist_ok=True)

def get_repo_path(project_id):
    return os.path.join(REPOS_DIR, project_id)

def run_git_cmd(repo_path, args):
    """Run a git command in the project repo safely using subprocess."""
    cmd = ["git"] + args
    try:
        res = subprocess.run(
            cmd,
            cwd=repo_path,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            timeout=10
        )
        return {"returncode": res.returncode, "stdout": res.stdout, "stderr": res.stderr}
    except Exception as e:
        return {"returncode": -1, "stdout": "", "stderr": str(e)}

def init_project_repo(project_id, title="Research Project", research_question="", description="", author_name="Lab Researcher", author_email="researcher@lab.local"):
    """Initialize a real Git repository for a research project."""
    repo_path = get_repo_path(project_id)
    if os.path.exists(os.path.join(repo_path, ".git")):
        return {"success": True, "repo_path": repo_path}
        
    os.makedirs(repo_path, exist_ok=True)
    
    # 1. git init
    run_git_cmd(repo_path, ["init"])
    run_git_cmd(repo_path, ["config", "user.name", author_name])
    run_git_cmd(repo_path, ["config", "user.email", author_email])
    
    # 2. Create initial project manifest
    readme_content = (
        f"# {title}\n\n"
        f"**Research Question:**\n{research_question or 'To be defined.'}\n\n"
        f"**Project Description:**\n{description or 'Collaborative investigation in AI Research Lab.'}\n\n"
        f"---\n"
        f"Generated by AI Research Lab IDE.\n"
    )
    with open(os.path.join(repo_path, "README.md"), "w", encoding="utf-8") as f:
        f.write(readme_content)
        
    gitignore_content = (
        "__pycache__/\n"
        "*.pyc\n"
        ".DS_Store\n"
        "*.tmp\n"
        "*.log\n"
    )
    with open(os.path.join(repo_path, ".gitignore"), "w", encoding="utf-8") as f:
        f.write(gitignore_content)
        
    # Subdirectories for upcoming phases
    os.makedirs(os.path.join(repo_path, "src"), exist_ok=True)
    os.makedirs(os.path.join(repo_path, "notes"), exist_ok=True)
    with open(os.path.join(repo_path, "src", ".gitkeep"), "w") as f:
        pass
    with open(os.path.join(repo_path, "notes", ".gitkeep"), "w") as f:
        pass

    # 3. Initial commit
    run_git_cmd(repo_path, ["add", "."])
    commit_res = run_git_cmd(repo_path, ["commit", "-m", "Initial research workspace repository setup"])
    
    return {"success": commit_res["returncode"] == 0, "repo_path": repo_path}

def get_commit_history(project_id, limit=20):
    """Retrieve real Git commit log for a project."""
    repo_path = get_repo_path(project_id)
    if not os.path.exists(os.path.join(repo_path, ".git")):
        init_project_repo(project_id)
        
    res = run_git_cmd(repo_path, [
        "log", 
        f"-n{limit}", 
        "--pretty=format:%H|%an|%ae|%cd|%s",
        "--date=short"
    ])
    
    if res["returncode"] != 0:
        return []
        
    commits = []
    for line in res["stdout"].strip().split("\n"):
        if not line.strip():
            continue
        parts = line.split("|", 4)
        if len(parts) == 5:
            commits.append({
                "hash": parts[0],
                "short_hash": parts[0][:7],
                "author_name": parts[1],
                "author_email": parts[2],
                "date": parts[3],
                "message": parts[4]
            })
    return commits

def get_project_file_tree(project_id):
    """Traverse project repository directory and return safe file listing."""
    repo_path = get_repo_path(project_id)
    if not os.path.exists(repo_path):
        init_project_repo(project_id)
        
    file_tree = []
    for root, dirs, files in os.walk(repo_path):
        # Exclude .git
        if ".git" in dirs:
            dirs.remove(".git")
            
        rel_dir = os.path.relpath(root, repo_path)
        if rel_dir == ".":
            rel_dir = ""
            
        for d in sorted(dirs):
            d_rel = os.path.join(rel_dir, d)
            file_tree.append({
                "name": d,
                "path": d_rel,
                "is_dir": True,
                "size": 0
            })
            
        for f in sorted(files):
            f_rel = os.path.join(rel_dir, f)
            full_path = os.path.join(root, f)
            size = os.path.getsize(full_path) if os.path.exists(full_path) else 0
            file_tree.append({
                "name": f,
                "path": f_rel,
                "is_dir": False,
                "size": size
            })
            
    return file_tree

def get_file_content(project_id, relative_path):
    """Read contents of a file within the project repository safely."""
    repo_path = get_repo_path(project_id)
    # Prevent directory traversal
    norm_path = os.path.normpath(relative_path)
    if norm_path.startswith("..") or os.path.isabs(norm_path):
        return {"success": False, "error": "Invalid file path."}
        
    full_path = os.path.join(repo_path, norm_path)
    if not os.path.exists(full_path) or os.path.isdir(full_path):
        return {"success": False, "error": "File not found."}
        
    try:
        with open(full_path, "r", encoding="utf-8", errors="replace") as f:
            content = f.read()
        return {"success": True, "path": norm_path, "content": content}
    except Exception as e:
        return {"success": False, "error": f"Failed to read file: {str(e)}"}

def save_and_commit_file(project_id, relative_path, content, message, author_name, author_email):
    """Write or update a file and create a Git commit."""
    repo_path = get_repo_path(project_id)
    norm_path = os.path.normpath(relative_path)
    if norm_path.startswith("..") or os.path.isabs(norm_path):
        return {"success": False, "error": "Invalid file path."}
        
    full_path = os.path.join(repo_path, norm_path)
    os.makedirs(os.path.dirname(full_path), exist_ok=True)
    
    with open(full_path, "w", encoding="utf-8") as f:
        f.write(content)
        
    run_git_cmd(repo_path, ["config", "user.name", author_name])
    run_git_cmd(repo_path, ["config", "user.email", author_email])
    run_git_cmd(repo_path, ["add", norm_path])
    
    commit_res = run_git_cmd(repo_path, ["commit", "-m", message.strip() or f"Update {norm_path}"])
    return {"success": commit_res["returncode"] == 0, "output": commit_res["stdout"]}
